
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace BudgetWebpage.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Budget
{

    public int Budget_ID { get; set; }

    public Nullable<int> Customer_ID { get; set; }

    public string Budget_Name { get; set; }

    public Nullable<decimal> Budget_Amount { get; set; }

    public string Budget_Category { get; set; }

    public Nullable<int> Month_Interval { get; set; }

    public Nullable<System.DateTime> Start_Date { get; set; }



    public virtual Customer Customer { get; set; }

}

}
