//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BudgetWebpage.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Budget
    {
        public int Budget_ID { get; set; }
        public Nullable<int> Customer_ID { get; set; }

        [Required(ErrorMessage = "Please enter a name.")]
        [Display(Name = "Budget Name")]
        public string Budget_Name { get; set; }

        [Required(ErrorMessage = "Please enter an amount.")]
        [Display(Name = "Budget Amount")]
        public Nullable<decimal> Budget_Amount { get; set; }

        [Required(ErrorMessage = "Please enter a category.")]
        [Display(Name = "Budget Category")]
        public string Budget_Category { get; set; }

        [Required(ErrorMessage = "Please enter an interval.")]
        [Display(Name = "Month Interval")]
        public Nullable<int> Month_Interval { get; set; }

        [Required(ErrorMessage = "Please enter a date.")]
        [Display(Name = "Start Date")]
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> Start_Date { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
