
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace BudgetWebpage.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Goal
{

    public int Goal_ID { get; set; }

    public int Customer_ID { get; set; }

    public string Account_Number { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public decimal Target_Amount { get; set; }

    public System.DateTime Start_Date { get; set; }

    public Nullable<System.DateTime> End_Date { get; set; }

    public bool Recurring_Status { get; set; }

    public Nullable<int> Interval_Num { get; set; }

    public string Interval_Type { get; set; }



    public virtual Account Account { get; set; }

    public virtual Customer Customer { get; set; }

}

}
