//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BudgetWebpage.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Transaction
    {
        [Display(Name = "Transaction ID")]
        public int Transaction_ID { get; set; }
        [Display(Name = "Account Type")]
        public string Account_Type { get; set; }
        [Display(Name = "Account Number")]
        public string Account_Number { get; set; }
        [Display(Name = "Processing Date")]
        [DataType(DataType.Date)]
        public System.DateTime Processing_Date { get; set; }
        [Display(Name = "Transaction Type")]
        public string Transaction_Type { get; set; }
        public decimal Amount { get; set; }

        public string Description { get; set; }

        public string Category { get; set; }

        public virtual Account Account { get; set; }
    }
}
